### ISSUE TITLE
blip2_t5_instruct check Error

### ISSUE THREAD

**Issue by Songinpyo** [lmb-freiburg/ovqa#1]
First of all, thanks for your great work!
It inspires me a lot :)

I have a question on load the "blip2_t5_instruct" model and run example.
I used your "check_all_models.py".

My environment info:
Linux
python=3.10
pytorch=2.1.0a0+b5021ba
cuda=12.1.

```bash
Run VQA inference for blip2_t5_instruct / flant5xl
Input image torch.Size([1, 3, 224, 224]) and question: what is this?
20240604 07:18:06 INFO Prompt: 'what is this?'
20240604 07:18:06 INFO Input ids: torch.Size([1, 5]) 0: [125, 19, 48, 58, 1]
20240604 07:18:06 INFO Decoded prompt: what is this?</s>
20240604 07:18:06 INFO Hyperparameters: do_sample=False, top_p=0.9, temperature=1, num_beams=5, max_new_tokens=256, min_new_tokens=1, repetition_penalty=1.5, length_penalty=1.0, num_return_sequences=1
Traceback (most recent call last):
  File "/home/work/InpyoSong/VQA/Methods/ovqa/check_all_models.py", line 121, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/work/InpyoSong/VQA/Methods/ovqa/check_all_models.py", line 90, in main
    answers = model.predict_answers(samples, prompt="{}")
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/work/InpyoSong/VQA/Methods/ovqa/ovqa/models/lavis/blip2_models/blip2_t5_instruct.py", line 282, in predict_answers
    return self.generate(samples, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/work/InpyoSong/VQA/Methods/ovqa/ovqa/models/lavis/blip2_models/blip2_t5_instruct.py", line 379, in generate
    outputs = self.t5_model.generate(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1452, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(
  File "/home/work/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 505, in _prepare_encoder_decoder_kwargs_for_generation
    model_kwargs["encoder_outputs"]: ModelOutput = encoder(**encoder_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
I  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/InpyoSong/VQA/Methods/ovqa/ovqa/models/lavis/blip2_models/modeling_t5.py", line 1120, in forward
    layer_outputs = layer_module(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/InpyoSong/VQA/Methods/ovqa/ovqa/models/lavis/blip2_models/modeling_t5.py", line 711, in forward
    self_attention_outputs = self.layer[0](
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/InpyoSong/VQA/Methods/ovqa/ovqa/models/lavis/blip2_models/modeling_t5.py", line 613, in forward
    normed_hidden_states = self.layer_norm(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/apex/normalization/fused_layer_norm.py", line 386, in forward
    return fused_rms_norm_affine(input, self.weight, self.normalized_shape, self.eps)
  File "/usr/local/lib/python3.10/dist-packages/apex/normalization/fused_layer_norm.py", line 189, in fused_rms_norm_affine
    return FusedRMSNormAffineFunction.apply(*args)
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/apex/normalization/fused_layer_norm.py", line 69, in forward
    output, invvar = fused_layer_norm_cuda.rms_forward_affine(
RuntimeError: expected scalar type Float but found BFloat16
```

I tried to use other apex version and torch version but those were not the solutions.
I'll lookforward your response.
Thank you.

**Comment by simon-ging** [comment]
Hi, happy to hear you like our work!

The model works on my end with an RTX3090 GPU. Maybe your GPU or driver is too old and does not support bfloat16?

Please check `python -c "import torch; print(torch.cuda.is_bf16_supported())"` (False=bfloat16 not supported)

In that case, the easiest solution would be to use a GPU that can run bfloat16 (or update drivers if necessary).

You could try running it in float32, but this would need quite a big GPU (probably you will run OOM) or run it on a CPU but that will be slow.  Also bfloat16 is hardcoded in that model (to verify this, see `ovqa/models/lavis/blip2_models/blip2_t5_instruct.py` and search for bfloat16) so you would need to change all those calls to float32.

As far as I know regular float16 will not work since the T5 model breaks in float16.

Hope this helps, closing for now, feel free to reopen if you need further assistance.

Kind regards,

Simon
